/**
 * Default form customization preset (template).
 * Used when an organization has no form_customizations row.
 * Based on CBFiguresHouse template — modern, clean design.
 */

import type { DesignSet } from "./stock-media";

export type FormTemplatePreset = {
  suggested_amounts: number[];
  allow_custom_amount: boolean;
  show_endowment_selection: boolean;
  header_text: string;
  subheader_text: string;
  thank_you_message: string | null;
  thank_you_video_url: string | null;
  thank_you_cta_url: string | null;
  thank_you_cta_text: string | null;
  primary_color: string | null;
  button_color: string | null;
  button_text_color: string | null;
  button_border_radius: string | null;
  header_image_url: string | null;
  font_family: string | null;
  design_sets: DesignSet[] | null;
  form_display_mode: "full" | "compressed" | "full_width";
  form_media_side: "left" | "right";
};

/** CBFiguresHouse-style template: clean, modern donation form defaults */
export const FORM_TEMPLATE_PRESET: FormTemplatePreset = {
  suggested_amounts: [10, 25, 50, 100, 250, 500],
  allow_custom_amount: true,
  show_endowment_selection: false,
  header_text: "Make a Donation",
  subheader_text: "Support our mission",
  thank_you_message: "Thank you for your generosity!",
  thank_you_video_url: null,
  thank_you_cta_url: null,
  thank_you_cta_text: null,
  primary_color: "#059669",
  button_color: "#059669",
  button_text_color: "#ffffff",
  button_border_radius: "12px",
  header_image_url: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&q=80",
  font_family: "barlow",
  design_sets: [
    {
      media_type: "image",
      media_url: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&q=80",
      title: "Make a Donation",
      subtitle: "Support our mission",
    },
  ],
  form_display_mode: "compressed",
  form_media_side: "left",
};

export type GivingFormTemplate = FormTemplatePreset & {
  id: string;
  name: string;
  description: string;
  embed_form_theme: string;
};

export const GIVING_FORM_TEMPLATES: GivingFormTemplate[] = [
  {
    id: "default-clean",
    name: "Clean Modern",
    description: "Modern, clean donation form with emerald accents",
    suggested_amounts: [10, 25, 50, 100, 250, 500],
    allow_custom_amount: true,
    show_endowment_selection: false,
    header_text: "Make a Donation",
    subheader_text: "Support our mission",
    thank_you_message: "Thank you for your generosity!",
    thank_you_video_url: null,
    thank_you_cta_url: null,
    thank_you_cta_text: null,
    primary_color: "#059669",
    button_color: "#059669",
    button_text_color: "#ffffff",
    button_border_radius: "12px",
    header_image_url: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&q=80",
    font_family: "barlow",
    design_sets: [
      {
        media_type: "image",
        media_url: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&q=80",
        title: "Make a Donation",
        subtitle: "Support our mission",
      },
    ],
    form_display_mode: "full",
    form_media_side: "left",
    embed_form_theme: "default",
  },
  {
    id: "grace-community",
    name: "Grace Community",
    description: "Dark navy panel with gold accents — matches Grace Community template",
    suggested_amounts: [25, 50, 100, 250, 500, 1000],
    allow_custom_amount: true,
    show_endowment_selection: false,
    header_text: "Give Securely Today",
    subheader_text: "Your giving makes a direct impact in our community and around the world.",
    thank_you_message: "Thank you for your generous gift!",
    thank_you_video_url: null,
    thank_you_cta_url: null,
    thank_you_cta_text: null,
    primary_color: "#C9A84C",
    button_color: "#C9A84C",
    button_text_color: "#1A1A2E",
    button_border_radius: "8px",
    header_image_url: "https://images.pexels.com/photos/6646918/pexels-photo-6646918.jpeg?auto=compress&cs=tinysrgb&w=800",
    font_family: null,
    design_sets: [
      {
        media_type: "image",
        media_url: "https://images.pexels.com/photos/6646918/pexels-photo-6646918.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Give Securely Today",
        subtitle: "Your giving makes a direct impact",
      },
    ],
    form_display_mode: "full_width",
    form_media_side: "left",
    embed_form_theme: "church-grace",
  },
  {
    id: "dark-elegant",
    name: "Dark Elegant",
    description: "Dark background with warm gold accents — matches Dark Elegant template",
    suggested_amounts: [25, 50, 100, 250, 500, 1000],
    allow_custom_amount: true,
    show_endowment_selection: false,
    header_text: "Support Our Ministry",
    subheader_text: "Your generosity fuels our mission and transforms lives.",
    thank_you_message: "Your generosity is deeply appreciated.",
    thank_you_video_url: null,
    thank_you_cta_url: null,
    thank_you_cta_text: null,
    primary_color: "#FBBF24",
    button_color: "#FBBF24",
    button_text_color: "#0F0F0F",
    button_border_radius: "8px",
    header_image_url: "https://images.pexels.com/photos/1586996/pexels-photo-1586996.jpeg?auto=compress&cs=tinysrgb&w=800",
    font_family: null,
    design_sets: [
      {
        media_type: "image",
        media_url: "https://images.pexels.com/photos/1586996/pexels-photo-1586996.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Support Our Ministry",
        subtitle: "Your generosity fuels our mission",
      },
    ],
    form_display_mode: "full_width",
    form_media_side: "left",
    embed_form_theme: "dark-elegant",
  },
  {
    id: "bold-contemporary",
    name: "Bold Contemporary",
    description: "Light card with bold red accents — matches Bold Contemporary template",
    suggested_amounts: [25, 50, 100, 250, 500, 1000],
    allow_custom_amount: true,
    show_endowment_selection: false,
    header_text: "Make a Gift",
    subheader_text: "Your generosity fuels every ministry and every life changed through the gospel.",
    thank_you_message: "Thank you for making a difference!",
    thank_you_video_url: null,
    thank_you_cta_url: null,
    thank_you_cta_text: null,
    primary_color: "#E63946",
    button_color: "#E63946",
    button_text_color: "#ffffff",
    button_border_radius: "10px",
    header_image_url: "https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=800",
    font_family: null,
    design_sets: [
      {
        media_type: "image",
        media_url: "https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Make a Gift",
        subtitle: "Every gift matters",
      },
    ],
    form_display_mode: "full_width",
    form_media_side: "left",
    embed_form_theme: "bold-contemporary",
  },
  {
    id: "modern-minimal",
    name: "Modern Minimal",
    description: "Clean sky-blue accents — matches Modern Minimal template",
    suggested_amounts: [10, 25, 50, 100, 250, 500],
    allow_custom_amount: true,
    show_endowment_selection: false,
    header_text: "Give Generously",
    subheader_text: "Your generosity enables us to serve our community and build God's kingdom.",
    thank_you_message: "Thank you for your generous gift!",
    thank_you_video_url: null,
    thank_you_cta_url: null,
    thank_you_cta_text: null,
    primary_color: "#0EA5E9",
    button_color: "#0EA5E9",
    button_text_color: "#ffffff",
    button_border_radius: "10px",
    header_image_url: "https://images.pexels.com/photos/3171837/pexels-photo-3171837.jpeg?auto=compress&cs=tinysrgb&w=800",
    font_family: null,
    design_sets: [
      {
        media_type: "image",
        media_url: "https://images.pexels.com/photos/3171837/pexels-photo-3171837.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Give Generously",
        subtitle: "Every gift makes a difference",
      },
    ],
    form_display_mode: "full",
    form_media_side: "left",
    embed_form_theme: "modern-minimal",
  },
  {
    id: "vibrant-community",
    name: "Vibrant Community",
    description: "Emerald green accents — matches Vibrant Community template",
    suggested_amounts: [25, 50, 100, 250, 500, 1000],
    allow_custom_amount: true,
    show_endowment_selection: false,
    header_text: "Give with Joy",
    subheader_text: "Your giving fuels our vibrant community and global outreach.",
    thank_you_message: "Thank you for your vibrant generosity!",
    thank_you_video_url: null,
    thank_you_cta_url: null,
    thank_you_cta_text: null,
    primary_color: "#059669",
    button_color: "#059669",
    button_text_color: "#ffffff",
    button_border_radius: "10px",
    header_image_url: "https://images.pexels.com/photos/6646918/pexels-photo-6646918.jpeg?auto=compress&cs=tinysrgb&w=800",
    font_family: null,
    design_sets: [
      {
        media_type: "image",
        media_url: "https://images.pexels.com/photos/6646918/pexels-photo-6646918.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Give with Joy",
        subtitle: "Fueling vibrant community impact",
      },
    ],
    form_display_mode: "full",
    form_media_side: "left",
    embed_form_theme: "vibrant-community",
  },
  {
    id: "serene-light",
    name: "Serene Light",
    description: "Soft purple accents — matches Serene Light template",
    suggested_amounts: [25, 50, 100, 250, 500, 1000],
    allow_custom_amount: true,
    show_endowment_selection: false,
    header_text: "Give in Peace",
    subheader_text: "Your offering brings peace and purpose to those in need.",
    thank_you_message: "Thank you for your peaceful generosity.",
    thank_you_video_url: null,
    thank_you_cta_url: null,
    thank_you_cta_text: null,
    primary_color: "#7C3AED",
    button_color: "#7C3AED",
    button_text_color: "#ffffff",
    button_border_radius: "10px",
    header_image_url: "https://images.pexels.com/photos/5206038/pexels-photo-5206038.jpeg?auto=compress&cs=tinysrgb&w=800",
    font_family: null,
    design_sets: [
      {
        media_type: "image",
        media_url: "https://images.pexels.com/photos/5206038/pexels-photo-5206038.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Give in Peace",
        subtitle: "Your offering brings peace and purpose",
      },
    ],
    form_display_mode: "full",
    form_media_side: "left",
    embed_form_theme: "serene-light",
  },
  {
    id: "urban-modern",
    name: "Urban Modern",
    description: "Indigo accents — matches Urban Modern template",
    suggested_amounts: [25, 50, 100, 250, 500, 1000],
    allow_custom_amount: true,
    show_endowment_selection: false,
    header_text: "Invest in Faith",
    subheader_text: "Your giving powers ministry in the heart of the city.",
    thank_you_message: "Thank you for investing in urban ministry!",
    thank_you_video_url: null,
    thank_you_cta_url: null,
    thank_you_cta_text: null,
    primary_color: "#6366F1",
    button_color: "#6366F1",
    button_text_color: "#ffffff",
    button_border_radius: "10px",
    header_image_url: "https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=800",
    font_family: null,
    design_sets: [
      {
        media_type: "image",
        media_url: "https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Invest in Faith",
        subtitle: "Powering ministry in the heart of the city",
      },
    ],
    form_display_mode: "full",
    form_media_side: "left",
    embed_form_theme: "urban-modern",
  },
  {
    id: "classic-reformed",
    name: "Classic Reformed",
    description: "Amber accents, serif typography — matches Classic Reformed template",
    suggested_amounts: [25, 50, 100, 250, 500, 1000],
    allow_custom_amount: true,
    show_endowment_selection: false,
    header_text: "Support the Mission",
    subheader_text: "Your faithful stewardship advances the gospel and strengthens our community.",
    thank_you_message: "Thank you for your faithful generosity!",
    thank_you_video_url: null,
    thank_you_cta_url: null,
    thank_you_cta_text: null,
    primary_color: "#B45309",
    button_color: "#B45309",
    button_text_color: "#ffffff",
    button_border_radius: "10px",
    header_image_url: "https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=800",
    font_family: null,
    design_sets: [
      {
        media_type: "image",
        media_url: "https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Support the Mission",
        subtitle: "Faithful stewardship, lasting impact",
      },
    ],
    form_display_mode: "full",
    form_media_side: "left",
    embed_form_theme: "classic-reformed",
  },
  {
    id: "organic-natural",
    name: "Organic Natural",
    description: "Green accents, rounded corners — matches Organic Natural template",
    suggested_amounts: [25, 50, 100, 250, 500, 1000],
    allow_custom_amount: true,
    show_endowment_selection: false,
    header_text: "Plant a Seed",
    subheader_text: "Your generosity nurtures growth in our community and beyond.",
    thank_you_message: "Thank you for planting seeds of generosity!",
    thank_you_video_url: null,
    thank_you_cta_url: null,
    thank_you_cta_text: null,
    primary_color: "#65A30D",
    button_color: "#65A30D",
    button_text_color: "#ffffff",
    button_border_radius: "16px",
    header_image_url: "https://images.pexels.com/photos/1072179/pexels-photo-1072179.jpeg?auto=compress&cs=tinysrgb&w=800",
    font_family: null,
    design_sets: [
      {
        media_type: "image",
        media_url: "https://images.pexels.com/photos/1072179/pexels-photo-1072179.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Plant a Seed",
        subtitle: "Nurturing growth in community",
      },
    ],
    form_display_mode: "full",
    form_media_side: "left",
    embed_form_theme: "organic-natural",
  },
  {
    id: "warm-heritage",
    name: "Warm Heritage",
    description: "Gold accents, sharp corners — matches Warm Heritage template",
    suggested_amounts: [25, 50, 100, 250, 500, 1000],
    allow_custom_amount: true,
    show_endowment_selection: false,
    header_text: "Honor Through Giving",
    subheader_text: "Continue the legacy of generosity that defines our community.",
    thank_you_message: "Thank you for honoring our heritage of giving!",
    thank_you_video_url: null,
    thank_you_cta_url: null,
    thank_you_cta_text: null,
    primary_color: "#D4AF37",
    button_color: "#D4AF37",
    button_text_color: "#3E2723",
    button_border_radius: "4px",
    header_image_url: "https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=800",
    font_family: null,
    design_sets: [
      {
        media_type: "image",
        media_url: "https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=800",
        title: "Honor Through Giving",
        subtitle: "A legacy of generosity",
      },
    ],
    form_display_mode: "full",
    form_media_side: "left",
    embed_form_theme: "warm-heritage",
  },
];
