export const LABEL_MAP: Record<string, Record<string, string>> = {
  weekly_attendance: {
    under_50: "Under 50",
    "50_150": "50–150",
    "151_300": "151–300",
    "301_500": "301–500",
    "501_1000": "501–1,000",
    "1000_plus": "1,000+",
  },
  org_type: {
    church: "Church",
    nonprofit: "Nonprofit",
    missionary: "Missionary",
    denomination: "Church network / denomination",
  },
  annual_budget: {
    under_100k: "Under $100k",
    "100k_250k": "$100k–$250k",
    "250k_500k": "$250k–$500k",
    "500k_1m": "$500k–$1M",
    "1m_plus": "$1M+",
  },
  biggest_challenges: {
    manual_payments: "Manual missionary payments",
    no_recurring: "No recurring giving",
    poor_donor_experience: "Poor donor experience",
    high_fees: "High fees",
    no_splits: "No splits to multiple recipients",
    hard_to_embed: "Hard to embed on website",
    other: "Other",
  },
  software_type: {
    all_in_one: "All-in-one",
    donation_only: "Donation-only",
    chms_addon: "ChMS add-on",
    mobile_app: "Mobile app",
    other: "Other",
  },
  top_features: {
    auto_splits: "Automated splits",
    recurring: "Recurring giving",
    embeddable_forms: "Embeddable forms",
    website_builder: "Website builder",
    custom_domains: "Custom domains",
    realtime_dashboard: "Real-time dashboard",
    donor_management: "Donor management",
    events_integration: "Events integration",
    other: "Other",
  },
  tech_type_needed: {
    software: "Software (web app)",
    streaming: "Streaming (live)",
    both: "Both",
    mobile_first: "Mobile-first",
    text_to_give: "Text-to-give",
    not_sure: "Not sure",
  },
  software_vs_streaming: {
    software_only: "Software only",
    streaming_only: "Streaming only",
    both: "Both",
    unsure: "Unsure",
  },
  better_ways_to_give: {
    one_tap_stream: "One-tap during stream",
    qr_code: "QR code",
    text_to_give: "Text-to-give",
    recurring: "Recurring auto-draft",
    split_funds: "Split to multiple funds",
    kiosk: "In-person kiosk",
    apple_google: "Apple Pay / Google Pay",
    other: "Other",
  },
  monthly_price_range: {
    free: "$0 (free)",
    "1_25": "$1–$25",
    "26_50": "$26–$50",
    "51_100": "$51–$100",
    "100_plus": "$100+",
  },
  switch_triggers: {
    lower_fees: "Lower fees",
    auto_splits: "Automated splits",
    better_ux: "Better UX",
    website_builder: "Website builder",
    missionary_support: "Missionary support",
    nothing: "Happy with current",
  },
  wish_tech_improved: {
    online_giving: "Online giving platforms",
    live_stream_giving: "Live-stream giving",
    church_website: "Church website builder",
    member_management: "Member / donor management",
    accounting: "Accounting & reporting",
    event_management: "Event management",
    volunteer_scheduling: "Volunteer scheduling",
    communication: "Communication tools",
    media_streaming: "Media / sermon streaming",
    mobile_app: "Church mobile app",
    other: "Other",
  },
  spend_to_solve_problem: {
    nothing: "$0 (free only)",
    under_25: "Under $25/mo",
    "25_50": "$25–$50/mo",
    "50_100": "$50–$100/mo",
    "100_200": "$100–$200/mo",
    "200_plus": "$200+/mo",
    one_time_500: "One-time up to $500",
    one_time_1000_plus: "One-time $1,000+",
  },
  networking_importance: {
    not_important: "Not important",
    somewhat: "Somewhat",
    very: "Very important",
    critical: "Critical",
  },
  paperwork_method: {
    all_paper: "All paper / printed",
    mix_paper_digital: "Mix paper & digital",
    mostly_digital: "Mostly digital",
    church_software: "Church management software",
    no_system: "No real system",
  },
  member_communication: {
    email: "Email newsletters",
    sms: "Text / SMS",
    social_media: "Social media",
    church_app: "Church app",
    bulletin: "Printed bulletin",
    word_of_mouth: "Word of mouth / calls",
    group_chat: "Group chat",
    website: "Church website",
    other: "Other",
  },
  ai_form_interest: {
    love_it: "Love it",
    interested: "Interested — want a demo",
    maybe: "Maybe — depends",
    not_interested: "Not interested",
    concerned: "Concerned about AI",
  },
  team_growth_tracking: {
    no_tracking: "Don't track it",
    informal: "Informal check-ins",
    small_groups: "Small-group feedback",
    surveys: "Periodic surveys",
    software: "Dedicated software",
  },
  congregation_engagement: {
    pastor_conversations: "Pastor conversations",
    small_groups: "Small-group leaders",
    prayer_cards: "Prayer request cards",
    attendance: "Attendance patterns",
    giving_patterns: "Giving patterns",
    social_media: "Social media",
    no_system: "No good system",
    would_love_help: "Would love a tool",
  },
  automation_needs: {
    auto_text_reminders: "Auto text reminders",
    auto_text_followup: "Auto text follow-ups",
    auto_email_newsletters: "Auto email newsletters",
    auto_email_receipts: "Auto donation receipts",
    drip_campaigns: "Drip campaigns",
    event_reminders: "Event RSVP reminders",
    birthday_anniversary: "Birthday/anniversary msgs",
    prayer_requests: "Auto prayer request collection",
    giving_nudges: "Giving reminders",
    none: "No automation needed",
  },
  campaign_tools_interest: {
    absolutely: "Absolutely",
    interested: "Interested",
    maybe: "Maybe",
    no: "No — prefer manual",
  },
  event_posting_needs: {
    desperately: "Desperately need this",
    would_help: "Would help",
    have_solution: "Already have a solution",
    not_needed: "Not needed",
  },
  teaching_packets_interest: {
    yes_weekly: "Yes — every week",
    yes_monthly: "Yes — monthly/events",
    maybe: "Maybe",
    no: "No — create our own",
  },
  ai_sermon_content: {
    amazing: "Amazing — huge time saver",
    try_it: "I'd try it",
    some_interest: "Somewhat interested",
    not_for_us: "Not for us",
    prefer_manual: "Prefer manual",
  },
  ai_member_curation: {
    revolutionary: "Revolutionary — I'd pay",
    very_interested: "Very interested",
    cautious: "Cautiously interested",
    not_needed: "Not needed",
    concerned: "Concerned about privacy",
  },
  pastor_approval_workflow: {
    must_approve: "Must approve everything",
    approve_first_then_trust: "Approve first, then trust",
    auto_fine: "Fully automatic is fine",
    not_interested: "Not interested",
  },
  member_development_tools: {
    spiritual_assessments: "Spiritual assessments",
    personalized_devotionals: "Personalized devotionals",
    small_group_matching: "AI small group matching",
    attendance_insights: "Attendance insights",
    giving_trends: "Giving trend analysis",
    milestone_tracking: "Milestone tracking",
    pastoral_alerts: "Pastoral care alerts",
    auto_check_ins: "Auto check-in messages",
    none: "None needed",
  },
  currently_live_stream: {
    yes_weekly: "Yes — every week",
    yes_sometimes: "Yes — sometimes",
    no_want_to: "No — want to start",
    no_not_interested: "No — not interested",
  },
  live_stream_platform: {
    youtube: "YouTube Live",
    facebook: "Facebook Live",
    church_app: "Church-specific app",
    zoom: "Zoom",
    multiple: "Multiple platforms",
    none: "None yet",
    other: "Other",
  },
  live_stream_giving_interest: {
    absolutely: "Absolutely",
    interested: "Interested",
    maybe: "Maybe",
    no: "No — keep separate",
  },
  live_stream_ai_features: {
    auto_forms: "Auto-create forms",
    sermon_notes: "Auto sermon notes",
    discussion_guides: "Discussion guides",
    quizzes_tests: "Quizzes / tests",
    devotionals: "Daily devotionals",
    action_items: "Extract action items",
    captions_transcript: "Captions & transcript",
    highlight_clips: "Auto highlight clips",
    member_followup: "Auto follow-up messages",
    none: "None",
  },
  live_stream_challenges: {
    tech_setup: "Tech setup too complex",
    cost: "Equipment / software cost",
    low_engagement: "Low viewer engagement",
    no_giving: "No giving during stream",
    no_interaction: "No viewer interaction",
    poor_quality: "Poor audio/video quality",
    no_follow_up: "No follow-up afterward",
    not_streaming: "Don't stream yet",
    none: "No challenges",
  },
  want_charts_dashboard: {
    yes_essential: "Essential",
    yes_nice: "Nice to have",
    maybe: "Maybe",
    no: "Not needed",
  },
  auto_giving_interest: {
    love_it: "Love it",
    interested: "Interested",
    cautious: "Cautious",
    no: "No — prefer manual",
  },
  auto_giving_features: {
    recurring_auto_draft: "Recurring auto-draft",
    auto_split_missionaries: "Auto splits to missionaries",
    auto_tax_receipts: "Auto tax receipts",
    auto_reports: "Auto financial reports",
    auto_fund_allocation: "Auto fund allocation",
    auto_payroll_pastoral: "Auto staff payroll",
    scheduled_transfers: "Scheduled bank transfers",
    pledge_tracking: "Pledge tracking",
    none: "None",
  },
  auto_transfer_fee_comfort: {
    yes_worth_it: "Yes — worth the time savings",
    yes_if_low: "Yes — if under $0.50",
    depends: "Depends on volume",
    no_fee: "No — fees are dealbreaker",
    pass_to_donor: "Only if donor covers fee",
  },
  website_tool_needs: {
    church_website: "Church website",
    online_giving_page: "Online giving page",
    event_posting: "Event posting",
    member_directory: "Member directory",
    sermon_archive: "Sermon archive",
    volunteer_signup: "Volunteer sign-ups",
    blog_updates: "Blog / news updates",
    live_stream: "Live stream integration",
    none: "No help needed",
  },
};

export function getLabel(field: string, value: string): string {
  return LABEL_MAP[field]?.[value] ?? value;
}
