import type { TypeformStepConfig } from "@/components/typeform-form";

export const SURVEY_STEPS: TypeformStepConfig[] = [
  // ── Section A: Church Profile ──
  {
    label: "What is your church's approximate weekly attendance?",
    name: "weekly_attendance",
    type: "select",
    required: true,
    options: [
      { value: "under_50", label: "Under 50" },
      { value: "50_150", label: "50–150" },
      { value: "151_300", label: "151–300" },
      { value: "301_500", label: "301–500" },
      { value: "501_1000", label: "501–1,000" },
      { value: "1000_plus", label: "1,000+" },
    ],
  },
  {
    label: "What type of organization are you?",
    name: "org_type",
    type: "radio",
    required: true,
    options: [
      { value: "church", label: "Church" },
      { value: "nonprofit", label: "Nonprofit" },
      { value: "missionary", label: "Missionary" },
      { value: "denomination", label: "Church network / denomination" },
    ],
  },
  {
    label: "What is your church's annual operating budget (approximate)?",
    name: "annual_budget",
    type: "select",
    required: true,
    options: [
      { value: "under_100k", label: "Under $100k" },
      { value: "100k_250k", label: "$100k–$250k" },
      { value: "250k_500k", label: "$250k–$500k" },
      { value: "500k_1m", label: "$500k–$1M" },
      { value: "1m_plus", label: "$1M+" },
    ],
  },
  {
    label: "How many staff members handle finances and giving?",
    name: "finance_staff_count",
    type: "select",
    required: true,
    options: [
      { value: "0", label: "0 (volunteer-run)" },
      { value: "1", label: "1" },
      { value: "2_3", label: "2–3" },
      { value: "4_plus", label: "4+" },
    ],
  },

  // ── Section B: Current Pain Points ──
  {
    label: "What is your biggest challenge with online giving today?",
    sublabel: "Select all that apply.",
    name: "biggest_challenges",
    type: "checkboxGroup",
    required: true,
    options: [
      { value: "manual_payments", label: "Manual missionary payments" },
      { value: "no_recurring", label: "No recurring giving" },
      { value: "poor_donor_experience", label: "Poor donor experience" },
      { value: "high_fees", label: "High fees" },
      { value: "no_splits", label: "No splits to multiple recipients" },
      { value: "hard_to_embed", label: "Hard to embed on website" },
      { value: "other", label: "Other" },
    ],
  },
  {
    label: "How many missionaries or partner organizations do you support financially?",
    name: "missionaries_supported",
    type: "select",
    required: true,
    options: [
      { value: "0", label: "0" },
      { value: "1_3", label: "1–3" },
      { value: "4_10", label: "4–10" },
      { value: "11_25", label: "11–25" },
      { value: "25_plus", label: "25+" },
    ],
  },
  {
    label: "How do you currently distribute funds to missionaries/partners?",
    name: "distribution_method",
    type: "radio",
    required: true,
    options: [
      { value: "manual_bank", label: "Manual bank transfers" },
      { value: "check", label: "Check" },
      { value: "paypal_venmo", label: "PayPal / Venmo" },
      { value: "platform_manual", label: "Donation platform with manual splits" },
      { value: "platform_auto", label: "Automated platform splits" },
      { value: "not_applicable", label: "Not applicable" },
    ],
  },
  {
    label: "How many hours per month do you spend on donation/finance admin?",
    name: "admin_hours_per_month",
    type: "select",
    required: true,
    options: [
      { value: "0_5", label: "0–5 hours" },
      { value: "6_10", label: "6–10 hours" },
      { value: "11_20", label: "11–20 hours" },
      { value: "21_40", label: "21–40 hours" },
      { value: "40_plus", label: "40+ hours" },
    ],
  },

  // ── Section C: Tech Preferences ──
  {
    label: "What type of software would best solve your giving needs?",
    name: "software_type",
    type: "radio",
    required: true,
    options: [
      { value: "all_in_one", label: "All-in-one (donations + website + splits)" },
      { value: "donation_only", label: "Donation-only platform" },
      { value: "chms_addon", label: "Add-on to existing church management (ChMS)" },
      { value: "mobile_app", label: "Mobile app for congregants" },
      { value: "other", label: "Other" },
    ],
  },
  {
    label: "Which features matter most to you?",
    sublabel: "Select up to 3.",
    name: "top_features",
    type: "checkboxGroup",
    required: true,
    options: [
      { value: "auto_splits", label: "Automated missionary splits" },
      { value: "recurring", label: "Recurring giving" },
      { value: "embeddable_forms", label: "Embeddable forms" },
      { value: "website_builder", label: "Website builder" },
      { value: "custom_domains", label: "Custom domains" },
      { value: "realtime_dashboard", label: "Real-time dashboard" },
      { value: "donor_management", label: "Donor management" },
      { value: "events_integration", label: "Events integration" },
      { value: "other", label: "Other" },
    ],
  },
  {
    label: "How important is connecting with other churches/nonprofits (networking)?",
    name: "networking_importance",
    type: "radio",
    required: true,
    options: [
      { value: "not_important", label: "Not important" },
      { value: "somewhat", label: "Somewhat important" },
      { value: "very", label: "Very important" },
      { value: "critical", label: "Critical" },
    ],
  },
  {
    label: "Do you have a church website today?",
    name: "has_website",
    type: "radio",
    required: true,
    options: [
      { value: "no", label: "No" },
      { value: "yes_basic", label: "Yes (basic)" },
      { value: "yes_advanced", label: "Yes (custom/advanced)" },
    ],
  },
  {
    label: "What type of tech do you feel you need for giving?",
    name: "tech_type_needed",
    type: "radio",
    required: true,
    options: [
      { value: "software", label: "Software (web app/dashboard)" },
      { value: "streaming", label: "Streaming (live giving during services)" },
      { value: "both", label: "Both software and streaming" },
      { value: "mobile_first", label: "Mobile-first app" },
      { value: "text_to_give", label: "Text-to-give" },
      { value: "not_sure", label: "Not sure" },
    ],
  },
  {
    label: "Is your ideal solution software-based or streaming/live-based?",
    name: "software_vs_streaming",
    type: "radio",
    required: true,
    options: [
      { value: "software_only", label: "Software only (manage donations, reports, recurring)" },
      { value: "streaming_only", label: "Streaming only (live giving during worship)" },
      { value: "both", label: "Both — software for management + streaming for services" },
      { value: "unsure", label: "Unsure" },
    ],
  },

  // ── Section C+ : Tech Wishlist & Budget ──
  {
    label: "What type of tech do you wish was more available or improved for churches?",
    sublabel: "Select all that apply.",
    name: "wish_tech_improved",
    type: "checkboxGroup",
    required: true,
    options: [
      { value: "online_giving", label: "Online giving / donation platforms" },
      { value: "live_stream_giving", label: "Live-stream integrated giving" },
      { value: "church_website", label: "Church website builder" },
      { value: "member_management", label: "Member / donor management (ChMS)" },
      { value: "accounting", label: "Accounting & financial reporting" },
      { value: "event_management", label: "Event management & ticketing" },
      { value: "volunteer_scheduling", label: "Volunteer scheduling" },
      { value: "communication", label: "Communication tools (email, SMS, push)" },
      { value: "media_streaming", label: "Media / sermon streaming" },
      { value: "mobile_app", label: "Church mobile app" },
      { value: "other", label: "Other" },
    ],
  },
  {
    label: "If a tool could solve your biggest giving problem, how much would you be willing to spend?",
    sublabel: "One-time or monthly — whichever feels right.",
    name: "spend_to_solve_problem",
    type: "radio",
    required: true,
    options: [
      { value: "nothing", label: "$0 — it needs to be free" },
      { value: "under_25", label: "Under $25/month" },
      { value: "25_50", label: "$25–$50/month" },
      { value: "50_100", label: "$50–$100/month" },
      { value: "100_200", label: "$100–$200/month" },
      { value: "200_plus", label: "$200+/month" },
      { value: "one_time_500", label: "A one-time fee up to $500" },
      { value: "one_time_1000_plus", label: "A one-time fee of $1,000+" },
    ],
  },

  // ── Section D: Better Ways to Handle Giving ──
  {
    label: "What are some better ways you would like to handle giving?",
    sublabel: "Select all that apply.",
    name: "better_ways_to_give",
    type: "checkboxGroup",
    required: true,
    options: [
      { value: "one_tap_stream", label: "One-tap giving during live stream" },
      { value: "qr_code", label: "QR code at pew/entrance" },
      { value: "text_to_give", label: "Text-to-give" },
      { value: "recurring", label: "Recurring auto-draft" },
      { value: "split_funds", label: "Split to multiple funds (general, building, missionary)" },
      { value: "kiosk", label: "In-person kiosk/tablet" },
      { value: "apple_google", label: "Apple Pay / Google Pay" },
      { value: "other", label: "Other" },
    ],
  },
  {
    label: "What would make giving easier for your congregation?",
    sublabel: "Share any ideas — we're listening.",
    name: "easier_giving_ideas",
    type: "textarea",
    placeholder: "e.g. Less friction, remember my info, give from phone during service…",
  },

  // ── Section E: Operations, Communication & AI ──
  {
    label: "How does your church currently manage paperwork (forms, sign-ups, volunteer sheets, etc.)?",
    name: "paperwork_method",
    type: "radio",
    required: true,
    options: [
      { value: "all_paper", label: "All paper / printed forms" },
      { value: "mix_paper_digital", label: "Mix of paper and digital (Google Forms, email)" },
      { value: "mostly_digital", label: "Mostly digital tools" },
      { value: "church_software", label: "Church management software (Planning Center, Breeze, etc.)" },
      { value: "no_system", label: "No real system — things fall through the cracks" },
    ],
  },
  {
    label: "How do you communicate with your members today?",
    sublabel: "Select all that apply.",
    name: "member_communication",
    type: "checkboxGroup",
    required: true,
    options: [
      { value: "email", label: "Email newsletters" },
      { value: "sms", label: "Text / SMS" },
      { value: "social_media", label: "Social media (Facebook, Instagram)" },
      { value: "church_app", label: "Church app" },
      { value: "bulletin", label: "Printed bulletin / announcements" },
      { value: "word_of_mouth", label: "Word of mouth / phone calls" },
      { value: "group_chat", label: "Group chat (GroupMe, WhatsApp)" },
      { value: "website", label: "Church website" },
      { value: "other", label: "Other" },
    ],
  },
  {
    label:
      "Would you be interested in AI that listens during a live stream or service, then automatically builds a form for members to fill out afterward?",
    sublabel:
      "For example: AI hears the pastor ask for prayer requests, then auto-creates and sends a prayer-request form to attendees.",
    name: "ai_form_interest",
    type: "radio",
    required: true,
    options: [
      { value: "love_it", label: "Love it — that would save us tons of time" },
      { value: "interested", label: "Interested — I'd want to see a demo" },
      { value: "maybe", label: "Maybe — depends on accuracy and cost" },
      { value: "not_interested", label: "Not interested" },
      { value: "concerned", label: "Concerned about AI in a church setting" },
    ],
  },
  {
    label: "How do you currently track that your team (staff + volunteers) is learning and growing spiritually?",
    name: "team_growth_tracking",
    type: "radio",
    required: true,
    options: [
      { value: "no_tracking", label: "We don't really track it" },
      { value: "informal", label: "Informal check-ins / conversations" },
      { value: "small_groups", label: "Small-group attendance and feedback" },
      { value: "surveys", label: "Periodic surveys or self-assessments" },
      { value: "software", label: "Dedicated software / discipleship platform" },
    ],
  },
  {
    label: "How do you know how your congregation is doing — spiritually and personally?",
    sublabel: "Select all that apply. We know pastors are busy, which is why AI could help.",
    name: "congregation_engagement",
    type: "checkboxGroup",
    required: true,
    options: [
      { value: "pastor_conversations", label: "One-on-one pastor conversations" },
      { value: "small_groups", label: "Small-group leaders report back" },
      { value: "prayer_cards", label: "Prayer request cards / forms" },
      { value: "attendance", label: "We track attendance patterns" },
      { value: "giving_patterns", label: "We notice giving patterns" },
      { value: "social_media", label: "Social media engagement" },
      { value: "no_system", label: "Honestly, we don't have a good system" },
      { value: "would_love_help", label: "We'd love a tool that helps with this" },
    ],
  },

  // ── Section F: Willingness to Pay ──
  {
    label: "What would you pay per month for a full donation platform?",
    sublabel: "Includes donations, splits, embeds, and a dashboard.",
    name: "monthly_price_range",
    type: "select",
    required: true,
    options: [
      { value: "free", label: "$0 (free only)" },
      { value: "1_25", label: "$1–$25" },
      { value: "26_50", label: "$26–$50" },
      { value: "51_100", label: "$51–$100" },
      { value: "100_plus", label: "$100+" },
    ],
  },
  {
    label: "Would you pay a percentage fee on each donation instead of (or in addition to) a monthly fee?",
    name: "percent_fee_preference",
    type: "radio",
    required: true,
    options: [
      { value: "prefer_percent", label: "Yes, prefer % fee" },
      { value: "under_2", label: "Yes, if under 2%" },
      { value: "flat_only", label: "No, prefer flat monthly only" },
      { value: "depends", label: "Depends on features" },
    ],
  },
  {
    label: "What would make you switch from your current giving solution?",
    sublabel: "Select all that apply.",
    name: "switch_triggers",
    type: "checkboxGroup",
    required: true,
    options: [
      { value: "lower_fees", label: "Lower fees" },
      { value: "auto_splits", label: "Automated splits" },
      { value: "better_ux", label: "Better UX" },
      { value: "website_builder", label: "Website builder" },
      { value: "missionary_support", label: "Missionary support" },
      { value: "nothing", label: "Nothing — happy with current" },
    ],
  },
];
